positive_compliments = [
    "You're like sunshine mixed with a brain! ☀️🧠",
    "You're rocking life like it's a runway. 💃",
    "You're code AND confidence goals. 👑",
    "You're the main character energy I needed today. 🎬",
    "You're smoother than a clean Git history. 🐱‍💼",
    "You light up the room like RGB on max settings. 💡🎨",
    "You're the commit that finally passed all tests. ✅",
    "You're the cherry on top of a perfect UI. 🍒",
    "You’re sharper than a semicolon in C. 🤮",
    "You're glowing brighter than a well-trained model. 🌟",
    "You're as rare as a zero-bug deployment. 🦤",
    "You're more refreshing than a dark theme at midnight. 🌌",
    "You’re more iconic than Ctrl + S. 📂",
    "You're the highlight of this repository. 🔥",
    "You're the cleanest syntax in this messy code world. 📜",
    "You debug life like a pro. 👩‍💻",
    "You're more efficient than a lambda function. 🔁",
    "You're sparkling like console output on success. ✨",
    "You are better than butter-smooth scrolling. 🧈",
    "You're like a push that never gets rejected. 🚀",
    "You're the ping to my pong. 🏓",
    "You're the passing test case in my CI/CD pipeline. 💖",
    "You’re brighter than a fresh install of Ubuntu. 💡🐧",
    "You're like a high-speed internet connection — unstoppable. ⚡",
    "You're as cool as a GPU on liquid cooling. ❄️",
    "You're the default dark mode in a world of light themes. 🌒"
]

neutral_compliments = [
    "You're holding it together like semicolons in JavaScript. 👏",
    "Even when quiet, you radiate good energy. 🌈",
    "You’re lowkey amazing — like a hidden Easter egg in code. 🥚✨",
    "Stable, calm, and quietly brilliant. That’s you. 🧘‍♀️",
    "You bring balance like a perfect indentation. 🧹",
    "You're like a background service — always running strong. 🔧",
    "You're the README of your own journey. 📖",
    "You’re calm like a well-handled exception. 🧘‍♂️",
    "You're the documentation I didn't know I needed. 📚",
    "You’re the helpful StackOverflow comment, not the answer — but still gold. 💬",
    "You're like a placeholder with purpose. 💡",
    "You're steady like a while loop with proper conditions. 🔁",
    "You're like middleware — holding it all together. 🔌",
    "You're default, but in the best way. 🧸",
    "You're like a class that just works. 🏷️"
]

negative_comforts = [
    "Hey, it’s okay to crash sometimes — even systems reboot stronger. 💪",
    "You're not broken, just debugging life. 🛠️💖",
    "Even in sadness, your soul still glows. 🌙",
    "You matter. Full stop. 💯",
    "Bad days pass — your light doesn’t. 🌅",
    "You're stronger than your worst bug. 🐞",
    "Every system needs maintenance — take your time. ⏳",
    "Even blue screens fade. You'll reboot. 💻",
    "Your worth isn’t based on uptime. 🌧️",
    "You're processing — and that’s okay. 🔄",
    "You still compile in my heart. 💘",
    "You're a patch away from power. ⚙️",
    "Even logs show progress in the mess. 🩵",
    "You're healing like a recovery mode champion. 🧬",
    "You're still a masterpiece — even with typos. ✍️"
]
