
positive_roasts = [
    "You're glowing like a bug near a zapper. 💡⚡",
    "You're so positive, even your syntax errors smile. 😅",
    "You're as bright as a screen at 3 AM — and just as annoying. 💡",
    "You're sunshine wrapped in spaghetti code. 🌞🍝",
    "You're on fire! Sadly, it's because your code crashed again. 🔥",
    "You're confident like someone who pushes to main without testing. 💀",
    "You're the main character... in a debugging tragedy. 🎭",
    "Your smile could power a server — until it segfaults. 😬",
    "You're like an AI model in training — hopeful, but still inaccurate. 🧠",
    "You're cheerful like a commit that says 'final', but we all know it's not. 🙃",
    "You're as fabulous as a Git conflict at 3AM. ✨",
    "You're as sweet as a '404 not found' on Valentine’s Day. 💘",
    "You shine like a brand new laptop — until the first update. 💻",
    "You're a rainbow in a dark theme IDE. 🌈",
    "You're like Python — mostly elegant but occasionally indentation-error. 🐍",
    "You're the cherry on top of a bug-ridden ice cream sundae. 🍒🍨",
    "You're smoother than an import from pandas. 🐼",
    "You're brighter than my screen in a pitch-black terminal. 💡",
    "You're on top of the world — too bad it's localhost. 🌍",
    "You're the dopamine hit after a passing test case. ✅",
    "You're more energetic than a fresh stack trace. ⚡",
    "You're as graceful as a TensorFlow update breaking everything. 😌",
    "You bring light like a new feature… that hasn't been tested yet. 💡",
    "You're like a fresh install of Python — clean and full of hope. 😍",
    "You're the sparkle in a freshly compiled program. ✨",
    "You're like a framework with zero bugs — mythical. 🦄",
    "You're coding like nobody's watching — and it shows. 🎉",
    "You debug with confidence… even when you're wrong. 👑",
    "You're like autocorrect — mostly helpful, sometimes hilarious. 🔤",
    "You're the caffeine of this team. ☕",
    "You're like a commit message that says ‘did something’. Mysteriously iconic. 📝",
    "You're floating through life like an unassigned pointer. 😇",
    "You're a walking StackOverflow… full of half-right answers. 📚",
    "You're like JavaScript — confusing but popular. 🥴",
    "You're sunshine on a loading spinner. 🌞🔄",
    "You're as chill as an idle thread. 🧘",
    "You're the emoji in a markdown file. 🖊️",
    "You're the ‘ping’ to my ‘pong’. 🏓",
    "You're as rare as code that runs on the first try. 🦖",
    "You're like a unicorn — if unicorns had merge conflicts. 🦄⚔️",
    "You're brighter than my LED strip setup. 🎇",
    "You're a vibe — and that vibe is debug mode. 🔍",
    "You're basically AI, but with more sass. 🤖💅",
    "You're the sparkle in a blinking cursor. ✨",
    "You're sunshine on a bug-fix Monday. 🌞🐞",
    "You're so radiant, you outshine my RGB keyboard. 🎮🌈",
    "You're the good kind of error — harmless and hilarious. 😂",
    "You're more brilliant than my search history after a coding error. 🧠🔍",
    "You're proof that joy exists… in a world of runtime errors. 💖",
    "You're living proof that confidence is 90% of coding. 💁‍♀️💻",
    "You're full of light — just like an overexposed selfie. 📸🌟"

    ]
neutral_roasts = [
        "You're like a default switch case — nobody uses you. 😐",
    "That was so neutral, it deserves a 'meh'. 😶",
    "You sound like AI wrote your diary. 🤖📓",
    "Your vibes are in safe mode. 🔄",
    "Did you just Ctrl + Z your personality? 🧍",
    "You're the human version of a loading bar. 🔄",
    "You're like a read-only file — untouchable and unchanging. 📁",
    "You're a floating comment — out of context and overlooked. 💬",
    "You're not boring, just... *buffering*. ⏳",
    "You're like an empty string — technically there, but... are you? 🧊",
    "You're like a keyboard with no backlight — invisible in the dark. 🌚⌨️",
    "You're as exciting as dry toast without butter. 🍞",
    "You're like a function that returns None. 🔁",
    "You're the pause button in an action movie. ⏸️",
    "You're like 'Lorem Ipsum' — placeholder energy. 📄",
    "You're a slow internet day in human form. 🐢",
    "You're like a calendar invite with no details. 🗓️❓",
    "You're the middle child of enthusiasm. 😐",
    "You're like Monday... just there. 🗓️😒",
    "You're like a snooze button. Predictable and slightly irritating. ⏰",
    "You're like a meeting with no agenda. 🙄",
    "You're the unflavored oatmeal of personalities. 🥣",
    "You're a neutral gear in a downhill race. 🚲",
    "You're like the ‘skip’ button… we all want to press it. ⏭️",
    "You're like a compiler with zero warnings... but no output either. 🧾",
    "You're like a spreadsheet with one row. 📊",
    "You're that one tab in Chrome we forgot to close. 🌐",
    "You're as dramatic as plain yogurt. 🥛",
    "You're the human equivalent of beige. 🎨",
    "You're a silent notification. 🔕",
    "You're the average in a data set of extremes. 📉",
    "You're like offline mode — still here, but not doing much. 📴",
    "You're as spicy as unsalted rice. 🍚",
    "You're like a log file: full of details nobody reads. 📃",
    "You're like a test case that always passes. Predictable. ✅",
    "You're the 'meh' emoji in a world of fire and sparkle. 😑",
    "You're a very well-balanced equation… emotionally. ➗",
    "You're the lowercase of enthusiasm. 🔠",
    "You're like a very safe for loop. Too safe. 🧼",
    "You're as flat as CSS without shadows. 🧾",
    "You're the sixth tab in a five-tab app. 😶‍🌫️",
    "You're like neutral pH. Not sour. Not sweet. Just... 🧪",
    "You're like a well-aligned div. Impressive, but unnoticed. 🧱",
    "You're a status update that no one reacts to. 💬0",
    "You're like Ctrl+Alt+Del with no response. ⌨️🧊",
    "You're the middle panel in a comic strip. Transitional. 📰",
    "You're the dots in a 'typing…' bubble. Forever waiting. 💭",
    "You're as calm as a sleeping CPU. 💤",
    "You're like a function that runs but no one calls. 🙃",
    "You're like an IDE with no extensions — basic and stable. 🧰",
    "You're neutral — the Switzerland of personality. 🇨🇭"
    ]
negative_roasts = [
        "You're so down bad, even your ML model underfits. 📉",
    "You're more unstable than my Wi-Fi. 📶❌",
    "Your sadness has more layers than a neural network. 🧠🧅",
    "Your life throws more exceptions than Python. 🚫",
    "Even your shadow left for better company. 🌑",
    "You debug like you’re playing Minesweeper. 💣",
    "You're the reason error logs are encrypted. 🧨",
    "You're like a broken loop — repeating your failures. 🔁",
    "You have less hope than a while(true) block. 😵",
    "You're like a corrupted dataset — unreadable. 📂",
    "You're crashing harder than my old Windows XP. 💥",
    "You're an outlier in sadness. 📊😭",
    "Your happiness got 404’d. ❌",
    "You’re like a server without uptime. Always down. 📴",
    "You're more lost than a semicolon in Python. 😖",
    "Even AI therapists gave up. 🧠🚫",
    "You handle life the way try-except handles bugs: you ignore it. 🧹",
    "Your energy is more drained than my laptop on 1%. 🔋",
    "You're like an expired SSL cert — not secure. 🧊",
    "You’re the 'else' after failure. 🪦",
    "Your face could launch a thousand exceptions. 🧨",
    "You're so negative, even your outputs return False. ❌",
    "You're one step away from deleting system32. 💀",
    "You're a broken stack trace in human form. 🧾",
    "You loop through pain like it’s your job. 🔁😭",
    "You’re like dead code — just... there. 🧟",
    "You're so empty, even null looks full. ⛔",
    "You're the ‘blue screen’ of my life. 💙💻",
    "You're darker than dark mode. 🌚",
    "Your attitude is more toxic than an untrained chatbot. 🤖☠️",
    "You're a dropped packet in the conversation. 📡",
    "You put the 'crash' in crash course. 🧱",
    "You're like a router in a thunderstorm — unstable. 🌩️",
    "You don’t just throw errors, you host them. 🛑",
    "Your debug process is just sobbing. 😭🪛",
    "You're a recursive problem with no base case. 🌀",
    "You bring more confusion than a misnamed variable. ❓",
    "You're so low, even the scrollbar can't reach you. 📉",
    "You make malware look friendly. 🐛",
    "You’re like a bootloop. Trying, failing, repeat. 🔄",
    "You're the reason Rage Quit was invented. 🎮💢",
    "You're not rock bottom. You're bedrock. 🪨",
    "You’re like a 0 accuracy model. Useless and sad. 😞",
    "You're the stack overflow in my heart. ❤️💔",
    "You're the unhandled exception in everyone’s day. 🚫",
    "You're less functional than a broken API. 🧩",
    "You debug like you’re negotiating with the code. 🤝",
    "You're like a bricked phone — can’t even restart. 📱💀",
    "You're a git push --force on happiness. ⛓️",
    "You emit more warning signals than a linter. ⚠️",
    "Even DNS can’t resolve your issues. 🌐"
    ]

